### ISSUE TITLE
Some method are incorrectly reported as never used

### ISSUE THREAD

**Issue by Bokoblin** [rtfpessoa/codacy-cppcheck#2]
Some methods of my project are incorrectly reported as never used though it's obviously not the case.
My files are split between .h and .cpp files in the same folder.
I've re-executed three times the analysis, but it's the same each time
![capture](https://cloud.githubusercontent.com/assets/8015512/25071480/9d3a80b4-22b0-11e7-8fa1-0c649147e8e2.JPG)
![capture](https://cloud.githubusercontent.com/assets/8015512/25071485/ef96fe8c-22b0-11e7-903b-caf95e8b8c02.JPG)

**Comment by rtfpessoa** [comment]
@Bokoblin since Codacy only runs CPPCheck for the changed files it cannot find if some methods are used.

We recommend you to disable those patterns to avoid false positives.
